server:
  port: 8083

spring:
  application:
    name: springcloud_coustomer
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: system
    password: miao1656
  main:
    allow-bean-definition-overriding: true

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
# 提供了断路器
feign:
  hystrix:
    enabled: true
